// Fake product data for the shop.
export const products = [
  {
    id: 1,
    name: 'Canvas Tote Bag',
    price: 28,
    category: 'Bags',
    image: 'https://picsum.photos/seed/tote-bag/400/400',
    description: 'A sturdy canvas tote for everyday errands and trips to the market.',
  },
  {
    id: 2,
    name: 'Wool Beanie',
    price: 22,
    category: 'Apparel',
    image: 'https://picsum.photos/seed/wool-beanie/400/400',
    description: 'Soft knit beanie made from 100% wool, warm enough for winter.',
  },
  {
    id: 3,
    name: 'Ceramic Mug',
    price: 14,
    category: 'Home',
    image: 'https://picsum.photos/seed/ceramic-mug/400/400',
    description: 'Hand-glazed ceramic mug, holds 12oz, dishwasher safe.',
  },
  {
    id: 4,
    name: 'Leather Wallet',
    price: 45,
    category: 'Accessories',
    image: 'https://picsum.photos/seed/leather-wallet/400/400',
    description: 'Slim bifold wallet made from full-grain leather.',
  },
  {
    id: 5,
    name: 'Cotton T-Shirt',
    price: 19,
    category: 'Apparel',
    image: 'https://picsum.photos/seed/cotton-tshirt/400/400',
    description: 'Classic fit t-shirt made from 100% organic cotton.',
  },
  {
    id: 6,
    name: 'Linen Throw Pillow',
    price: 32,
    category: 'Home',
    image: 'https://picsum.photos/seed/throw-pillow/400/400',
    description: 'Soft linen pillow cover, 18x18 inches, hidden zipper.',
  },
  {
    id: 7,
    name: 'Canvas Backpack',
    price: 64,
    category: 'Bags',
    image: 'https://picsum.photos/seed/backpack/400/400',
    description: 'Durable canvas backpack with padded laptop sleeve.',
  },
  {
    id: 8,
    name: 'Sunglasses',
    price: 38,
    category: 'Accessories',
    image: 'https://picsum.photos/seed/sunglasses/400/400',
    description: 'UV-protective sunglasses with a matte acetate frame.',
  },
  {
    id: 9,
    name: 'Wool Scarf',
    price: 26,
    category: 'Apparel',
    image: 'https://picsum.photos/seed/wool-scarf/400/400',
    description: 'Lightweight wool scarf, one size, five colors available.',
  },
];